### ISSUE TITLE
Files for tent-able middle layers please

### ISSUE THREAD

**Issue by jimmyhchan** [keebio/iris-case#2]
https://www.reddit.com/r/MechanicalKeyboards/comments/7c9jpp/ic_smashing_acrylics_iris_and_nyquist_cases/dporhc2/

Pretty please, would you share the middle layers that are tent-able.

**Comment by nooges** [comment]
Added it in now: https://github.com/keebio/iris-case/blob/master/iris-middle-layer-tent.ai

**Comment by kohlerm** [comment]
This file is gone on master.  The V3 file seems to have different sizes for the usb port. Does it still work?
