### ISSUE TITLE
Issue with the 3-D Case

### ISSUE THREAD

**Issue by CommonSenseUsed** [keebio/iris-case#21]
@CharlesLenk whenever I render the model I get no top-level geometry to render. Is there a fix for this? I changed the user configurable options to 

`two_unit_thumb = false;`
`stabilizers = true;`
`usb_c_pro_micro = false;`
`trrs_diameter = 6.55;`
`selector = 5;`

**Comment by CharlesLenk** [comment]
You're right! Sorry about that, there's a missing call to draw the case. Adding the following call after the user defined options will fix the issue: `drawCase();`

I'll get a PR in to correct this as well.

**Comment by CharlesLenk** [comment]
Ah, I see you already found it. Thanks for submitting the change! I don't have merge permissions, but I've added an approval for what it counts.

**Comment by nooges** [comment]
Fixed with PR
