### ISSUE TITLE
[Request] Upload files that made the STLs for Phoenix Edition middle layers

### ISSUE THREAD

**Issue by Zomgnomes** [keebio/iris-case#37]
As the title says, please upload the file you used to generate the STLs for the PE middle layers.  

The triangulation on the STLs is kind of jacked up and it makes doing simple things like adding a chamfer to the bottom edge, and adding a lip to make a more sandwich style case that doesn't need the top bit a kind of massive pain.

**Comment by nooges** [comment]
I've added the F360 files used to generate the STLs here: https://github.com/keebio/iris-case/tree/master/phoenix-edition-PE/f360
