### ISSUE TITLE
Ponoko stroke width?

### ISSUE THREAD

**Issue by gwerbin** [keebio/iris-case#5]
Ponoko's laser cuts a 0.01mm stroke. Do the design files need to be adjusted for that? It seems awfully tiny -- it's barely visible in Inkscape unless I zoom in to almost 200%.

The generated SVGs are [here](https://github.com/gwerbin/iris-case/tree/4e00ae68ce2a17e364ff3a293b6c9c4233285e92/vector).

**Comment by geoah** [comment]
@gwerbin did you try to get these cut with ponoko? Wondering how they came out.

**Comment by gwerbin** [comment]
I didn't get these plates cut but I did get a custom design (via Swillkb) done by Ponoko. I didn't set a kerf in Swillkb, and the switches fit pretty well.

I'm not sure if that helps at all. Maybe I can compare the switch openings in the Iris file to the ones in my file and adjust accordingly.

But now that you've teased the Rorschach maybe I'll put this whole idea on hold ;)

**Comment by nooges** [comment]
Yeah, when generating files for Ponoko, you need to set the color of the lines to blue and set stroke width to 0.01mm. It's not really the cutting width of their laser, it's just the format that they'd like the files to be in.
