### ISSUE TITLE
Confirm dimensions for sculpteo

### ISSUE THREAD

**Issue by Jennetters** [keebio/iris-case#6]
Hi There, I was uploading the middle layer to sculpteo, however when I try to add the dimensions specified, their software forces me to a fixed aspect ratio of 155.3mm x 133.9mm or 153.7mm x 132.5mm. 

Could you please confirm that the dimensions need to be 153.7mm x 133.9mm. If so, do you have suggestions for how to get around the fixed aspect? Thanks.

**Comment by nooges** [comment]
For the middle layer, the height is shorter, due to the USB cutouts at the top. I used the dimensions of 153.7mm x 132.5mm.
