### ISSUE TITLE
Update README for tented case

### ISSUE THREAD

**Issue by kevinduffey** [keebio/iris-case#7]
The current README indicates the middle, bottom and switch layers  for a case.  Yet, there is a tented version, which when I enter in the Sculpteo  site, indicates  slightly  different dimensions than what the info  says. I assume  its right  since I can not adjust the  2nd dimension as  it auto-adjusts when I enter the 153.7 dimension data  in. 

It is not clear if the top layer is ALSO needed, or it that is only for the TENTED version middle layer.

**Comment by nooges** [comment]
Done
