### ISSUE TITLE
Middle layer tent has  different dimensions in Sculpteo

### ISSUE THREAD

**Issue by kevinduffey** [keebio/iris-case#9]
The middle layer tented file indicates a  slightly  small dimension which can not  be   adjusted  on the Sculpteo site. Are the dimensions correct?

153.7 × 121.8 mm

**Comment by geoah** [comment]
I'm currently dealing with the same issue :D 

I can only assume that the scale just needs to be the same with the rest, which is `26.5%`.
With this scale the height comes down to `132.5mm` which is the same as the suggested for the non-tent middle layer.

So I assume that tent middle layer is `167.2mm x 132.5mm`.

**Comment by nooges** [comment]
Added the dimensions to the README in bd8124c742f3b9c94d986b8c2a66fabdf8fd7629
